import{useMemo,useState}from"react";import{providers}from"./data.js";
const FY=["F27","F26","F25","F24"],metrics=[["project","Project Progress","purple","▥"],["edrm","EDRM Progress","teal","▱"],["inventory","Inventory Progress","blue","□"],["destruction","Destruction Progress","orange","♻"]];
const clamp=v=>Math.min(100,Math.max(0,Number(v)||0));
function Bar({value,tone}){return <div className="track"><i className={tone} style={{width:`${clamp(value)}%`}}/></div>}
function Donut({value,tone,label,big=false}){return <div className="donut-item"><div className={`donut ${tone} ${big?"big":""}`} style={{"--v":clamp(value)}}><b>{clamp(value)}%</b></div><strong>{label}</strong></div>}
function Fiscal({value,setValue}){return <label className="fiscal"><span>Fiscal Year</span><select value={value} onChange={e=>setValue(e.target.value)}>{FY.map(y=><option key={y}>{y}</option>)}</select></label>}
function SocCards({soc}){const a=[["Scope",soc.scope,"◎"],["Audit Period",soc.auditPeriod,"▣"],["SOC 2 Report",soc.report,"▤"],["Remediation Plan",soc.remediationPlan,"✓"],["Status Update",soc.statusUpdate,"◷"],["Next Fiscal Year Scope",soc.nextFiscalYearScope,"→"]];return <div className="soc-cards">{a.map(([l,v,i])=><article key={l}><header><em>{i}</em><h3>{l}</h3></header><p>{v}</p></article>)}</div>}
function Header({p,id,setId}){return <header className="top"><div><small>Gaming Data Initiative</small><h1>Reporting Dashboard</h1><p>{p.name} <span>({p.abbreviation})</span></p></div><label><span>Change Provider</span><select value={id} onChange={e=>setId(e.target.value)}>{providers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label></header>}
function Overview({p,fy,setFy,latest,setView}){const soc=p.soc2History[fy];return <><section className="kpis">{metrics.map(([k,l,t,i])=><article key={k}><div><h2>{l}</h2><em className={t}>{i}</em></div><b>{p.metrics[k]}%</b><Bar value={p.metrics[k]} tone={t}/><small>Current completion</small></article>)}</section><section className="dashboard-grid">
<article className="panel inventory"><h2><em>◷</em>Inventory Progress</h2><div className="inv-content"><div className="donuts"><h3>Structured and Unstructured Progress</h3><div><Donut value={p.inventory.structured} tone="teal" label="Structured" big/><Donut value={p.inventory.unstructured} tone="blue" label="Unstructured" big/></div></div><div className="breakdown"><h3>Unstructured Data Inventory Breakdown</h3><div className="row"><span>Physical</span><Bar value={p.inventory.physical} tone="teal"/><b>{p.inventory.physical}%</b></div><div className="row"><span>Electronic</span><Bar value={p.inventory.electronic} tone="purple"/><b>{p.inventory.electronic}%</b></div></div></div></article>
<div className="middle-stack"><article className="panel destruction"><h2><em>♻</em>Destruction Progress</h2><div className="destroy-body"><Donut value={p.destruction.overall} tone="orange" label="Overall"/><div><div className="row"><span>Structured</span><Bar value={p.destruction.structured} tone="red"/><b>{p.destruction.structured}%</b></div><div className="row"><span>Unstructured</span><Bar value={p.destruction.unstructured} tone="orange"/><b>{p.destruction.unstructured}%</b></div></div></div></article><article className="panel updates"><div className="panel-head"><h2><em>◷</em>Project Progress Updates</h2><button onClick={()=>setView("updates")}>View history →</button></div><div className="update-scroll"><ul>{latest.map((u,i)=><li key={i}>{u.text}</li>)}</ul></div></article></div>
<article className="panel soc"><div className="panel-head"><h2><em>✓</em>SOC 2 Type II Status</h2><div><Fiscal value={fy} setValue={setFy}/><button onClick={()=>setView("soc2")}>View details →</button></div></div><SocCards soc={soc}/></article></section></>}
function SocDetail({p,fy,setFy}){return <section className="detail"><div className="panel detail-head"><div><small>Detailed assurance view</small><h2>SOC 2 Type II Status</h2><p>Review current and historical fiscal-year information.</p></div><Fiscal value={fy} setValue={setFy}/></div><div className="panel"><SocCards soc={p.soc2History[fy]}/></div></section>}
function Updates({p}){const groups=useMemo(()=>p.updates.reduce((a,u)=>((a[u.date]??=[]).push(u),a),{}),[p]);return <section className="detail"><div className="panel detail-head"><div><small>Complete provider history</small><h2>Project Progress Updates</h2></div></div>{Object.entries(groups).sort(([a],[b])=>b.localeCompare(a)).map(([d,us])=><article className="panel history" key={d}><time>{new Date(`${d}T12:00:00`).toLocaleDateString("en-CA",{year:"numeric",month:"long",day:"numeric"})}</time><ul>{us.map((u,i)=><li key={i}>{u.text}</li>)}</ul></article>)}</section>}
export default function App(){const[id,setId]=useState("gce"),[view,setView]=useState("overview"),[fy,setFy]=useState("F27");const p=providers.find(x=>x.id===id)||providers[0];const latest=useMemo(()=>{const d=p.updates.reduce((m,u)=>u.date>m?u.date:m,p.updates[0]?.date||"");return p.updates.filter(u=>u.date===d)},[p]);return <div><aside><b>GDI</b><nav><button className={view==="overview"?"active":""} onClick={()=>setView("overview")}>▦<span>Overview</span></button><button className={view==="soc2"?"active":""} onClick={()=>setView("soc2")}>✓<span>SOC 2</span></button><button className={view==="updates"?"active":""} onClick={()=>setView("updates")}>◷<span>Updates</span></button></nav></aside><main><Header p={p} id={id} setId={setId}/>{view==="overview"&&<Overview p={p} fy={fy} setFy={setFy} latest={latest} setView={setView}/>} {view==="soc2"&&<SocDetail p={p} fy={fy} setFy={setFy}/>} {view==="updates"&&<Updates p={p}/>}<footer>GDI Reporting Dashboard · Prototype data only</footer></main></div>}
