import{useMemo,useState}from"react";import{providers}from"./data.js";
const FY=["F27","F26","F25","F24"];
const KPI=[{key:"project",label:"Project Progress",icon:"project-progress.png",color:"#142fa4",soft:"#eef0ff"},{key:"edrm",label:"EDRM Progress",icon:"edrm-progress.png",color:"#6a26a5",soft:"#f3eafa"},{key:"inventory",label:"Inventory Progress",icon:"inventory-progress.png",color:"#1a9b5a",soft:"#e8f7ef"},{key:"destruction",label:"Destruction Progress",icon:"destruction-progress.png",color:"#f01808",soft:"#fff0ec"}];
const clamp=v=>Math.min(100,Math.max(0,Number(v)||0));
function Progress({value,color}){return <div className="progress"><i style={{width:`${clamp(value)}%`,background:color}}/></div>}
function Donut({value,color,label,size="large"}){const n=clamp(value);return <div className={`donut-unit ${size}`}><div className="donut" style={{"--value":n,"--color":color}}><b>{n}%</b></div><span>{label}</span></div>}
function Selector({label,value,onChange,children,className=""}){return <label className={`selector ${className}`}><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>}
function Header({provider,providerId,setProviderId}){return <header className="page-header"><div><p>Gaming Data Initiative</p><h1>Reporting Dashboard</h1><span>{provider.name} <em>({provider.abbreviation})</em></span></div><Selector label="Change Provider" value={providerId} onChange={setProviderId}>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Selector></header>}
function SectionTitle({icon,title,action,iconClass=""}){return <div className="section-title"><div><span className={`section-image ${iconClass}`}><img src={`./icons/${icon}`} alt=""/></span><h2>{title}</h2></div>{action}</div>}
function KpiRow({provider}){return <section className="kpi-grid">{KPI.map(k=><article className="kpi-card" key={k.key} style={{"--accent":k.color,"--soft":k.soft}}><div className="kpi-icon"><img src={`./icons/${k.icon}`} alt=""/></div><div className="kpi-content"><h2>{k.label}</h2><strong>{provider.metrics[k.key]}%</strong><Progress value={provider.metrics[k.key]} color={k.color}/><small>Current completion</small></div></article>)}</section>}
function InventoryPanel({provider}){return <article className="panel inventory-panel"><SectionTitle icon="inventory-progress.png" title="Inventory Progress"/><div className="inventory-layout"><div className="donut-area"><h3>Structured and Unstructured Progress</h3><div><Donut value={provider.inventory.structured} color="#1a9b5a" label="Structured"/><Donut value={provider.inventory.unstructured} color="#142fa4" label="Unstructured"/></div></div><div className="inventory-breakdown"><h3>Unstructured Data Inventory Breakdown</h3><div className="bar-item"><div><span>Physical</span><b>{provider.inventory.physical}%</b></div><Progress value={provider.inventory.physical} color="#1779ba"/></div><div className="bar-item"><div><span>Electronic</span><b>{provider.inventory.electronic}%</b></div><Progress value={provider.inventory.electronic} color="#7557d6"/></div></div></div></article>}
function DestructionPanel({provider}){return <article className="panel destruction-panel"><SectionTitle icon="destruction-progress.png" title="Destruction Progress" iconClass="orange-icon"/><div className="destruction-layout"><Donut value={provider.destruction.overall} color="#f59e0b" label="Overall" size="medium"/><div className="destruction-bars"><div className="bar-item"><div><span>Structured</span><b>{provider.destruction.structured}%</b></div><Progress value={provider.destruction.structured} color="#f59e0b"/></div><div className="bar-item"><div><span>Unstructured</span><b>{provider.destruction.unstructured}%</b></div><Progress value={provider.destruction.unstructured} color="#f59e0b"/></div></div></div></article>}
function UpdatesPanel({updates,onOpen}){return <article className="panel updates-panel"><SectionTitle icon="project-progress.png" title="Project Progress Update" action={<button className="detail-link" onClick={onOpen}>View history ›</button>}/><div className="update-body"><ul>{updates.map((u,i)=><li key={`${u.date}-${i}`}>{u.text}</li>)}</ul></div></article>}
const socFields=s=>[["Scope",s.scope],["Audit Period",s.auditPeriod],["SOC 2 Report",s.report],["Remediation Plan",s.remediationPlan],["Status Update",s.statusUpdate],["Next Fiscal Year Scope",s.nextFiscalYearScope]];
function SocPanel({soc,fiscalYear,setFiscalYear,onOpen,detailed=false}){return <article className={`panel soc-panel ${detailed?"soc-detailed":""}`}><SectionTitle icon="soc2-status.png" title="SOC 2 Type II Status" action={<div className="soc-actions"><Selector label="Fiscal Year" value={fiscalYear} onChange={setFiscalYear} className="fy-selector">{FY.map(y=><option key={y}>{y}</option>)}</Selector>{!detailed&&<button className="detail-link" onClick={onOpen}>View details ›</button>}</div>}/><div className="soc-grid">{socFields(soc).map(([label,value])=><div className="soc-item" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div></article>}
function Overview({provider,latest,fiscalYear,setFiscalYear,setView}){return <><KpiRow provider={provider}/><section className="dashboard-grid"><InventoryPanel provider={provider}/><DestructionPanel provider={provider}/><UpdatesPanel updates={latest} onOpen={()=>setView("updates")}/><SocPanel soc={provider.soc2History[fiscalYear]} fiscalYear={fiscalYear} setFiscalYear={setFiscalYear} onOpen={()=>setView("soc2")}/></section></>}
function SocDetail({provider,fiscalYear,setFiscalYear,onBack}){return <section className="detail-page"><button className="back" onClick={onBack}>‹ Back to dashboard</button><SocPanel soc={provider.soc2History[fiscalYear]} fiscalYear={fiscalYear} setFiscalYear={setFiscalYear} detailed/></section>}
function UpdatesDetail({provider,onBack}){const groups=useMemo(()=>provider.updates.reduce((a,u)=>{(a[u.date]??=[]).push(u);return a},{}),[provider]);return <section className="detail-page"><button className="back" onClick={onBack}>‹ Back to dashboard</button><article className="panel history-panel"><SectionTitle icon="project-progress.png" title="Project Progress Update History"/><div>{Object.entries(groups).sort(([a],[b])=>b.localeCompare(a)).map(([date,items])=><section className="history-group" key={date}><time>{new Date(`${date}T12:00:00`).toLocaleDateString("en-CA",{year:"numeric",month:"long",day:"numeric"})}</time><ul>{items.map((u,i)=><li key={i}>{u.text}</li>)}</ul></section>)}</div></article></section>}
export default function App(){const[providerId,setProviderId]=useState("gce"),[fiscalYear,setFiscalYear]=useState("F27"),[view,setView]=useState("overview");const provider=providers.find(p=>p.id===providerId)||providers[0];const latest=useMemo(()=>{const d=provider.updates.reduce((m,u)=>u.date>m?u.date:m,provider.updates[0]?.date||"");return provider.updates.filter(u=>u.date===d)},[provider]);return <div className="app"><main><Header provider={provider} providerId={providerId} setProviderId={setProviderId}/>{view==="overview"&&<Overview provider={provider} latest={latest} fiscalYear={fiscalYear} setFiscalYear={setFiscalYear} setView={setView}/>} {view==="soc2"&&<SocDetail provider={provider} fiscalYear={fiscalYear} setFiscalYear={setFiscalYear} onBack={()=>setView("overview")}/>} {view==="updates"&&<UpdatesDetail provider={provider} onBack={()=>setView("overview")}/>}</main><footer>GDI Reporting Dashboard · Prototype data only · Production values will come from Dataverse</footer></div>}
